# Site Settings
title: Drew Alleman's Blog
description: A personal blog by Drew Alleman, sharing insights on software development, security, penetration testing, and software engineering.
baseurl: "" 
url: "https://drewalleman.xyz" 
author: Drew Alleman

# SEO settings
lang: en
logo: /assets/images/logo.png
twitter:
  username: your_twitter_handle
  card: summary_large_image

# Open Graph
og_image: /assets/images/og-default.jpg
social:
  name: Drew Alleman
  links:
    - https://github.com/Drew-Alleman
    - https://www.youtube.com/@drewalleman
    - https://www.linkedin.com/in/drew-alleman-909352209